<a href="https://colab.research.google.com/github/Vasudev-SN/MPEA_dataset/blob/master/Housing_data_Regression_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data',header=None,delim_whitespace=True)

In [ ]:
data

0     1      2   3      4      5     6       7   8      9     10  \
0    0.00632  18.0   2.31   0  0.538  6.575  65.2  4.0900   1  296.0  15.3   
1    0.02731   0.0   7.07   0  0.469  6.421  78.9  4.9671   2  242.0  17.8   
2    0.02729   0.0   7.07   0  0.469  7.185  61.1  4.9671   2  242.0  17.8   
3    0.03237   0.0   2.18   0  0.458  6.998  45.8  6.0622   3  222.0  18.7   
4    0.06905   0.0   2.18   0  0.458  7.147  54.2  6.0622   3  222.0  18.7   
..       ...   ...    ...  ..    ...    ...   ...     ...  ..    ...   ...   
501  0.06263   0.0  11.93   0  0.573  6.593  69.1  2.4786   1  273.0  21.0   
502  0.04527   0.0  11.93   0  0.573  6.120  76.7  2.2875   1  273.0  21.0   
503  0.06076   0.0  11.93   0  0.573  6.976  91.0  2.1675   1  273.0  21.0   
504  0.10959   0.0  11.93   0  0.573  6.794  89.3  2.3889   1  273.0  21.0   
505  0.04741   0.0  11.93   0  0.573  6.030  80.8  2.5050   1  273.0  21.0   

         11    12    13  
0    396.90  4.98  24.0  
1    396.90  9.14  21.6  
2    392.83  4.03  34.7  
3    394.63  2.94  33.4  
4    396.90  5.33  36.2  
..      ...   ...   ...  
501  391.99  9.67  22.4  
502  396.90  9.08  20.6  
503  396.90  5.64  23.9  
504  393.45  6.48  22.0  
505  396.90  7.88  11.9  

[506 rows x 14 columns]

In [ ]:
data.describe

<bound method NDFrame.describe of           0     1      2   3      4      5     6       7   8      9     10  \
0    0.00632  18.0   2.31   0  0.538  6.575  65.2  4.0900   1  296.0  15.3   
1    0.02731   0.0   7.07   0  0.469  6.421  78.9  4.9671   2  242.0  17.8   
2    0.02729   0.0   7.07   0  0.469  7.185  61.1  4.9671   2  242.0  17.8   
3    0.03237   0.0   2.18   0  0.458  6.998  45.8  6.0622   3  222.0  18.7   
4    0.06905   0.0   2.18   0  0.458  7.147  54.2  6.0622   3  222.0  18.7   
..       ...   ...    ...  ..    ...    ...   ...     ...  ..    ...   ...   
501  0.06263   0.0  11.93   0  0.573  6.593  69.1  2.4786   1  273.0  21.0   
502  0.04527   0.0  11.93   0  0.573  6.120  76.7  2.2875   1  273.0  21.0   
503  0.06076   0.0  11.93   0  0.573  6.976  91.0  2.1675   1  273.0  21.0   
504  0.10959   0.0  11.93   0  0.573  6.794  89.3  2.3889   1  273.0  21.0   
505  0.04741   0.0  11.93   0  0.573  6.030  80.8  2.5050   1  273.0  21.0   

         11    12    13  
0  

In [ ]:
from keras.layers import Dense, Activation
from keras import Sequential
import tensorflow 
import keras

In [ ]:
data.isnull()

0      1      2      3      4      5      6      7      8      9   \
0    False  False  False  False  False  False  False  False  False  False   
1    False  False  False  False  False  False  False  False  False  False   
2    False  False  False  False  False  False  False  False  False  False   
3    False  False  False  False  False  False  False  False  False  False   
4    False  False  False  False  False  False  False  False  False  False   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
501  False  False  False  False  False  False  False  False  False  False   
502  False  False  False  False  False  False  False  False  False  False   
503  False  False  False  False  False  False  False  False  False  False   
504  False  False  False  False  False  False  False  False  False  False   
505  False  False  False  False  False  False  False  False  False  False   

        10     11     12     13  
0    False  False  False  False  
1    False  False  False  False  
2    False  False  False  False  
3    False  False  False  False  
4    False  False  False  False  
..     ...    ...    ...    ...  
501  False  False  False  False  
502  False  False  False  False  
503  False  False  False  False  
504  False  False  False  False  
505  False  False  False  False  

[506 rows x 14 columns]

In [ ]:
data.describe()

0           1           2           3           4           5   \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

               6           7           8           9           10          11  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

               12          13  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()


In [ ]:
X = data.values[:,0:13]
Y=data.values[:,13]
# Y = data[13]
type(X)

numpy.ndarray

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()
model.add(Dense(13, input_shape=(13,), kernel_initializer='normal'))
model.add(Dense(1, kernel_initializer='normal' ))

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 13)                182       
                                                                 
 dense_3 (Dense)             (None, 1)                 14        
                                                                 
Total params: 196
Trainable params: 196
Non-trainable params: 0
_________________________________________________________________


In [ ]:
import tensorflow as tf

In [ ]:
model.compile(loss='mean_squared_error', optimizer='adam')

In [ ]:
X

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [ ]:
Y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [ ]:
X.shape

(506, 13)

In [ ]:
Y.shape

(506,)

In [ ]:
X.ndim


2

In [ ]:
Y.ndim

1

In [ ]:
model.fit(X,Y,epochs=70,verbose=1)

Epoch 1/70
16/16 [==============================] - 1s 2ms/step - loss: 481.1891
Epoch 2/70
16/16 [==============================] - 0s 2ms/step - loss: 181.0927
Epoch 3/70
16/16 [==============================] - 0s 2ms/step - loss: 120.8294
Epoch 4/70
16/16 [==============================] - 0s 3ms/step - loss: 108.4330
Epoch 5/70
16/16 [==============================] - 0s 2ms/step - loss: 98.3567
Epoch 6/70
16/16 [==============================] - 0s 2ms/step - loss: 90.7979
Epoch 7/70
16/16 [==============================] - 0s 2ms/step - loss: 84.3610
Epoch 8/70
16/16 [==============================] - 0s 3ms/step - loss: 79.3037
Epoch 9/70
16/16 [==============================] - 0s 5ms/step - loss: 75.3540
Epoch 10/70
16/16 [==============================] - 0s 6ms/step - loss: 72.9481
Epoch 11/70
16/16 [==============================] - 0s 3ms/step - loss: 71.5833
Epoch 12/70
16/16 [==============================] - 0s 3ms/step - loss: 70.6831
Epoch 13/70
16/16 [==============

In [ ]:
y_pred=model.predict(X)

16/16 [==============================] - 0s 4ms/step


In [ ]:
y_pred

array([[28.269648  ],
       [24.781065  ],
       [26.687225  ],
       [26.485193  ],
       [25.929708  ],
       [25.944475  ],
       [22.064308  ],
       [20.810629  ],
       [13.228684  ],
       [20.677906  ],
       [19.724302  ],
       [23.298794  ],
       [16.649     ],
       [24.033035  ],
       [24.58644   ],
       [23.201035  ],
       [21.292892  ],
       [21.444439  ],
       [14.900607  ],
       [22.407806  ],
       [18.192408  ],
       [22.976347  ],
       [20.148079  ],
       [19.991407  ],
       [21.892824  ],
       [17.477629  ],
       [21.84171   ],
       [17.65791   ],
       [24.431059  ],
       [24.037266  ],
       [16.251795  ],
       [24.12133   ],
       [ 7.171622  ],
       [19.144484  ],
       [14.344161  ],
       [23.564352  ],
       [20.935637  ],
       [21.312384  ],
       [19.12721   ],
       [30.954676  ],
       [32.170105  ],
       [19.510166  ],
       [18.794683  ],
       [18.091528  ],
       [19.964193  ],
       [18

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
model.evaluate(x=X,y=y_pred)

16/16 [==============================] - 0s 3ms/step - loss: 2.7352e-12


2.7352243733846926e-12